"""
Utilities package
"""

from .error_codes import (
    error_response,
    success_response,
    ERR_MISSING_FILE,
    ERR_MISSING_PARAM,
    ERR_INVALID_PARAM,
    ERR_INVALID_FILE_TYPE,
    ERR_QUIZ_NOT_FOUND,
    ERR_SESSION_NOT_FOUND,
    ERR_QUESTION_NOT_FOUND,
    ERR_SESSION_EXPIRED,
    ERR_SESSION_ALREADY_SUBMITTED,
    ERR_INVALID_ANSWER,
    ERR_VALIDATION_FAILED,
    ERR_IMPORT_FAILED,
    ERR_DUPLICATE_QUIZ,
    ERR_CALCULATION_ERROR,
    ERR_INTERNAL,
)

__all__ = [
    'error_response',
    'success_response',
    'ERR_MISSING_FILE',
    'ERR_MISSING_PARAM',
    'ERR_INVALID_PARAM',
    'ERR_INVALID_FILE_TYPE',
    'ERR_QUIZ_NOT_FOUND',
    'ERR_SESSION_NOT_FOUND',
    'ERR_QUESTION_NOT_FOUND',
    'ERR_SESSION_EXPIRED',
    'ERR_SESSION_ALREADY_SUBMITTED',
    'ERR_INVALID_ANSWER',
    'ERR_VALIDATION_FAILED',
    'ERR_IMPORT_FAILED',
    'ERR_DUPLICATE_QUIZ',
    'ERR_CALCULATION_ERROR',
    'ERR_INTERNAL',
]
